#!/bin/bash

# This section is quite messy and complex
dirs=$(ls -l | grep '^d' | awk '{print $NF}')
matching_dirs=$(echo "$dirs" | grep  "20[12][0-9]")
highest_dir=$(echo "$matching_dirs" | sort -t' ' -k2,2nr | tail -n 1)

cd "$highest_dir"

next_dir=$(ls -l | grep '^d' | awk '{print $NF}' | tail -n 1)
cd "$next_dir"

file=$(ls part*.ts | tail -n 1)

if [ -z "$1" ]; then
    ARG1="--debug"
else
    ARG1="$1"
fi

bun "$file" "$ARG1"

cd ../..

